### ISSUE TITLE
Getting Error on running code npm start

### ISSUE THREAD

**Issue by saviomartin** [dhruv-kumar-jha/snake-ladder#1]
After installing all dependencies,
I ran the code
```
npm start
```
I got errors
```
saviomartin:~/Desktop/snake-ladder-master$ npm start

> snake-ladder@1.0.0 start /home/acer/Desktop/snake-ladder-master
> node production.js

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at Function.listen (/home/acer/Desktop/snake-ladder-master/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/home/acer/Desktop/snake-ladder-master/production.js:16:5)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snake-ladder@1.0.0 start: `node production.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snake-ladder@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/acer/.npm/_logs/2020-09-09T12_21_09_071Z-debug.log
```
Help me🤝

**Comment by dhruv-kumar-jha** [comment]
@saviomartin This could mean you already have something running on port 80, try changing the port in https://github.com/dhruv-kumar-jha/snake-ladder/blob/master/production.js file

You can change the port in line 7, Replace 80 with something else and run `npm start` again.

```
Ex change app.set( 'port', process.env.PORT || 80 ); to
app.set( 'port', process.env.PORT || 3000 );
```

Now the app should be running at port 3000, `http://localhost:3000/`

---

If this doesn't fix the issue, run npm start with sudo in the beginning or with admin privileges in windows.

**Comment by saviomartin** [comment]
No bro, There is nothing running on port **80**

**Comment by dhruv-kumar-jha** [comment]
> No bro, There is nothing running on port **80**

Either change the port or run the command with admin privileges.

**Comment by saviomartin** [comment]
I have changed the **port** and it  worked, **geat work** bro
```app.set( 'port', process.env.PORT || 3000 );```
